name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    # Also checkout https://github.com/raspberrypi/pico-sdk.git
    - uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
    # Set the PICO_SDK environment variable to the path of the pico-sdk repository
    - run: apt update
    - run: apt install cmake ninja gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
    - run: cmake -G Ninja -B build -DPICO_SDK_PATH=${GITHUB_WORKSPACE}/pico-sdk
